### ISSUE TITLE
2.0.0计划表

### ISSUE THREAD

**Issue by Executor-Cheng** [Executor-Cheng/Mirai-CSharp#53]
直接跳major版本了
~~可能会弃用`.NET Standard 2.0`&`.NET Framework 4.6.1`的支持, 要实现依赖注入的消息框架, 默认接口实现功能不可缺少~~
> 予以支持

~~也可能弃用掉`MiraiSession`里边的所有events~~
> 考虑公开一个接口, 接口成员均为`event`

- [x] 使用依赖注入重新设计本项目(#48 )
- [ ] 添加native支持(#22 )
- [ ] 支持mirai Code Specification - mirai 码(#2 )
- [ ] ~~考虑转化所有EventArgs为record(#24 )~~ (不予支持。继承方面有一些问题)
- [x] 为await添加ConfigureAwait(#51 )
- [x] 实现合并转发(#49 )
- [x] 更改主要命名空间为`Mirai.CSharp` (#57 )
- [x] 重写示例

**Comment by Executor-Cheng** [comment]
开发分支为`preview/2.0.0`
`Mirai-CSharp.HttpApi`项目将对标`mirai-api-http,v2.0`

**Comment by SlimeNull** [comment]
有一说一, 对于命名空间的更改, 你只需要使用 F2 先将命名空间 "Mirai_CSharp" 更改为一个不可能出现在别的地方的字符串, 例如 "Mirai_CSharp_Temp_JF68F4FEW684FEWO1", 然后用 Ctrl + H, 直接替换掉解决方案中所有这个字符串为 "Mirai.CSharp" 就可以

**Comment by aion1998** [comment]
建议制造一个C#模板，穿nuget去
